name: Build and Test
on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v3
      - name: Build with Gradle
        run: ./gradlew build
