name: Lint and Format
on: [push, pull_request]

jobs:
  spotless:
    name: Spotless
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v3
      - name: Check format with Spotless
        run: ./gradlew spotlessCheck
